# -*- coding: utf-8 -*-
"""BOQ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rsvIHCqbPg7cooPxHu9hecKNLa1RX5so
"""

!git clone https://github.com/surya9teja/BOQ.git

print("1. 24F")
print("2. 48F")
print("3. 24F&48F")
options=int(input("Choose option: "))
#ht=float(input("Height of the Tower: "))
sl=float(input("Splicing Lenght(m): "))
el=float(input("Extra length(m): "))
mf=float(input("multiply factor for OPGW total length: "))
rs=float(input("Rulling span length(m): "))
tw=float(input("Tension tower(%): "))
sw=100-int(tw)
dl=input("Drum Lenght(Km): ")
print ("Splicing Lenght(m):",sl)
print ("Extra lenght:",el)
print ("Percentage extra for OPGW:",mf)
print ("Rulling span lenght:",rs)
print ("Tension tower:",tw)
print ("suspension tower:",sw)
print ("Drum Lenght(Km):", dl)

import openpyxl
wb=openpyxl.load_workbook('/content/rse.xlsx')
sheet=wb.active
max_rows=sheet.max_row
max_columns=sheet.max_column
for row_number in range(2,max_rows+1):
  if sheet.cell(row=row_number, column=3).value==400:
    tower_height=35
    #Tower Height
    sheet.cell(row=row_number, column=16).value=tower_height
    #Actual OPGW from excel sheet
    opgw_route_length=sheet.cell(row=row_number, column=4).value
    #Joint box
    sheet.cell(row=row_number, column=14).value=round(1+(float(sheet.cell(row=row_number, column=4).value)/float(dl)))
    joint_box=sheet.cell(row=row_number, column=14).value
    #Total Length for 400KV so tower height = 35m
    sheet.cell(row=row_number, column=5).value=((opgw_route_length*1000*mf)+((tower_height*2)+sl+el)*(joint_box-1))/1000
    total_lenth=sheet.cell(row=row_number, column=5).value
    #Total Towers
    sheet.cell(row=row_number, column=6).value=round(1+(float(sheet.cell(row=row_number, column=4).value*1000))/rs)
    total_towers=sheet.cell(row=row_number, column=6).value
    #Tension Towers
    sheet.cell(row=row_number, column=7).value=round((total_towers*tw)/100)
    tension_towers=sheet.cell(row=row_number, column=7).value
    #Suspension Towers
    sheet.cell(row=row_number, column=8).value=round(total_towers-((total_towers*tw)/100))
    suspension_towers=sheet.cell(row=row_number, column=8).value
    #single suspension assembly
    sheet.cell(row=row_number, column=9).value=suspension_towers
    single_suspension_assembly=suspension_towers
    #single tension assembly for dead end location 
    sheet.cell(row=row_number, column=10).value=2
    single_tension_assembly_dead_end= sheet.cell(row=row_number, column=10).value
    #Double tension assembly for joint box location
    sheet.cell(row=row_number, column=11).value=joint_box-single_tension_assembly_dead_end
    double_tension_assembly_joint_box_location= sheet.cell(row=row_number, column=11).value
    #Double tension assembly for pass through
    sheet.cell(row=row_number, column=12).value=tension_towers-(single_tension_assembly_dead_end+double_tension_assembly_joint_box_location)
    double_tension_assembly_pass_through=sheet.cell(row=row_number, column=12).value
    #Vibration damper wirh protection rod
    sheet.cell(row=row_number, column=13).value=tension_towers*4+suspension_towers*2
    vibration_damper=sheet.cell(row=row_number, column=13).value
    #Surplus cable support
    sheet.cell(row=row_number, column=15).value=joint_box
    surplus_cable_support=sheet.cell(row=row_number, column=15).value
    #Downlead Clamp
    sheet.cell(row=row_number, column=17).value=surplus_cable_support*round(tower_height/2)
    downlead_clamp=sheet.cell(row=row_number, column=17).value
    #FODP
    sheet.cell(row=row_number, column=18).value=2
    fodp=sheet.cell(row=row_number, column=18).value
    #Approach Cable
    sheet.cell(row=row_number, column=19).value=fodp*500
    approach_cable=sheet.cell(row=row_number, column=19).value
    #HDPE Duct
    sheet.cell(row=row_number, column=20).value=approach_cable-(15*fodp)
    hdpe=sheet.cell(row=row_number, column=20).value
    #End Plug
    sheet.cell(row=row_number, column=21).value=fodp
    end_plug=sheet.cell(row=row_number, column=21).value
    #pushift couple
    sheet.cell(row=row_number, column=22).value=end_plug*5
    pushift_couple=sheet.cell(row=row_number, column=22).value
    #cable sealing
    sheet.cell(row=row_number, column=23).value=end_plug
    #U clamp
    sheet.cell(row=row_number, column=24).value=end_plug*25  
  elif sheet.cell(row=row_number, column=3).value==220:
    tower_height=40
    #Tower Height
    sheet.cell(row=row_number, column=16).value=tower_height
    #Actual OPGW from excel sheet
    opgw_route_length=sheet.cell(row=row_number, column=4).value
    #Joint box
    sheet.cell(row=row_number, column=14).value=round(1+(float(sheet.cell(row=row_number, column=4).value)/float(dl)))
    joint_box=sheet.cell(row=row_number, column=14).value
    #Total Length for 400KV so tower height = 35m
    sheet.cell(row=row_number, column=5).value=((opgw_route_length*1000*mf)+((tower_height*2)+sl+el)*(joint_box-1))/1000
    total_lenth=sheet.cell(row=row_number, column=5).value
    #Total Towers
    sheet.cell(row=row_number, column=6).value=round(1+(float(sheet.cell(row=row_number, column=4).value*1000))/rs)
    total_towers=sheet.cell(row=row_number, column=6).value
    #Tension Towers
    sheet.cell(row=row_number, column=7).value=round((total_towers*tw)/100)
    tension_towers=sheet.cell(row=row_number, column=7).value
    #Suspension Towers
    sheet.cell(row=row_number, column=8).value=round(total_towers-((total_towers*tw)/100))
    suspension_towers=sheet.cell(row=row_number, column=8).value
    #single suspension assembly
    sheet.cell(row=row_number, column=9).value=suspension_towers
    single_suspension_assembly=suspension_towers
    #single tension assembly for dead end location 
    sheet.cell(row=row_number, column=10).value=2
    single_tension_assembly_dead_end= sheet.cell(row=row_number, column=10).value
    #Double tension assembly for joint box location
    sheet.cell(row=row_number, column=11).value=joint_box-single_tension_assembly_dead_end
    double_tension_assembly_joint_box_location= sheet.cell(row=row_number, column=11).value
    #Double tension assembly for pass through
    sheet.cell(row=row_number, column=12).value=tension_towers-(single_tension_assembly_dead_end+double_tension_assembly_joint_box_location)
    #Vibration damper wirh protection rod
    sheet.cell(row=row_number, column=13).value=tension_towers*4+suspension_towers*2
    vibration_damper=sheet.cell(row=row_number, column=13).value
    #Surplus cable support
    sheet.cell(row=row_number, column=15).value=joint_box
    surplus_cable_support=sheet.cell(row=row_number, column=15).value
    #Downlead Clamp
    sheet.cell(row=row_number, column=17).value=surplus_cable_support*round(tower_height/2)
    downlead_clamp=sheet.cell(row=row_number, column=17).value
    #FODP
    sheet.cell(row=row_number, column=18).value=2
    fodp=sheet.cell(row=row_number, column=18).value
    #Approach Cable
    sheet.cell(row=row_number, column=19).value=fodp*500
    approach_cable=sheet.cell(row=row_number, column=19).value
    #HDPE Duct
    sheet.cell(row=row_number, column=20).value=approach_cable-(15*fodp)
    hdpe=sheet.cell(row=row_number, column=20).value
    #End Plug
    sheet.cell(row=row_number, column=21).value=fodp
    end_plug=sheet.cell(row=row_number, column=21).value
    #pushift couple
    sheet.cell(row=row_number, column=22).value=end_plug*5
    pushift_couple=sheet.cell(row=row_number, column=22).value
    #cable sealing
    sheet.cell(row=row_number, column=23).value=end_plug
    #U clamp
    sheet.cell(row=row_number, column=24).value=end_plug*25
  else:
    tower_height=35
    #Tower Height
    sheet.cell(row=row_number, column=16).value=tower_height
    #Actual OPGW from excel sheet
    opgw_route_length=sheet.cell(row=row_number, column=4).value
    #Joint box
    sheet.cell(row=row_number, column=14).value=round(1+(float(sheet.cell(row=row_number, column=4).value)/float(dl)))
    joint_box=sheet.cell(row=row_number, column=14).value
    #Total Length for 400KV so tower height = 35m
    sheet.cell(row=row_number, column=5).value=((opgw_route_length*1000*mf)+((tower_height*2)+sl+el)*(joint_box-1))/1000
    total_lenth=sheet.cell(row=row_number, column=5).value
    #Total Towers
    sheet.cell(row=row_number, column=6).value=round(1+(float(sheet.cell(row=row_number, column=4).value*1000))/rs)
    total_towers=sheet.cell(row=row_number, column=6).value
    #Tension Towers
    sheet.cell(row=row_number, column=7).value=round((total_towers*tw)/100)
    tension_towers=sheet.cell(row=row_number, column=7).value
    #Suspension Towers
    sheet.cell(row=row_number, column=8).value=round(total_towers-((total_towers*tw)/100))
    suspension_towers=sheet.cell(row=row_number, column=8).value
    #single suspension assembly
    sheet.cell(row=row_number, column=9).value=suspension_towers
    single_suspension_assembly=suspension_towers
    #single tension assembly for dead end location 
    sheet.cell(row=row_number, column=10).value=2
    single_tension_assembly_dead_end= sheet.cell(row=row_number, column=10).value
    #Double tension assembly for joint box location
    sheet.cell(row=row_number, column=11).value=joint_box-single_tension_assembly_dead_end
    double_tension_assembly_joint_box_location= sheet.cell(row=row_number, column=11).value
    #Double tension assembly for pass through
    sheet.cell(row=row_number, column=12).value=tension_towers-(single_tension_assembly_dead_end+double_tension_assembly_joint_box_location)
    #Vibration damper wirh protection rod
    sheet.cell(row=row_number, column=13).value=tension_towers*4+suspension_towers*2
    vibration_damper=sheet.cell(row=row_number, column=13).value
    #Surplus cable support
    sheet.cell(row=row_number, column=15).value=joint_box
    surplus_cable_support=sheet.cell(row=row_number, column=15).value
    #Downlead Clamp
    sheet.cell(row=row_number, column=17).value=surplus_cable_support*round(tower_height/2)
    downlead_clamp=sheet.cell(row=row_number, column=17).value
    #FODP
    sheet.cell(row=row_number, column=18).value=2
    fodp=sheet.cell(row=row_number, column=18).value
    #Approach Cable
    sheet.cell(row=row_number, column=19).value=fodp*500
    approach_cable=sheet.cell(row=row_number, column=19).value
    #HDPE Duct
    sheet.cell(row=row_number, column=20).value=approach_cable-(15*fodp)
    hdpe=sheet.cell(row=row_number, column=20).value
    #End Plug
    sheet.cell(row=row_number, column=21).value=fodp
    end_plug=sheet.cell(row=row_number, column=21).value
    #pushift couple
    sheet.cell(row=row_number, column=22).value=end_plug*5
    pushift_couple=sheet.cell(row=row_number, column=22).value
    #cable sealing
    sheet.cell(row=row_number, column=23).value=end_plug
    #U clamp
    sheet.cell(row=row_number, column=24).value=end_plug*25
  wb.save('test2.xlsx')

import openpyxl
wb=openpyxl.load_workbook('/content/example.xlsx')
sheet=wb.active
max_rows=sheet.max_row
max_columns=sheet.max_column
def Fiber_24():
  for row_number in range(2,max_rows+1):
    if sheet.cell(row=row_number, column=3).value==400:
      tower_height=40
      #Tower Height
      sheet.cell(row=row_number, column=16).value=tower_height
      #Actual OPGW from excel sheet
      opgw_route_length=sheet.cell(row=row_number, column=4).value
      #Joint box
      sheet.cell(row=row_number, column=14).value=round(1+(float(sheet.cell(row=row_number, column=4).value)/float(dl)))
      joint_box=sheet.cell(row=row_number, column=14).value
      #Total Length for 400KV so tower height = 35m
      sheet.cell(row=row_number, column=5).value=((opgw_route_length*1000*mf)+((tower_height*2)+sl+el)*(joint_box-1))/1000
      total_lenth=sheet.cell(row=row_number, column=5).value
      #Total Towers
      sheet.cell(row=row_number, column=6).value=round(1+(float(sheet.cell(row=row_number, column=4).value*1000))/rs)
      total_towers=sheet.cell(row=row_number, column=6).value
      #Tension Towers
      sheet.cell(row=row_number, column=7).value=round((total_towers*tw)/100)
      tension_towers=sheet.cell(row=row_number, column=7).value
      #Suspension Towers
      sheet.cell(row=row_number, column=8).value=round(total_towers-((total_towers*tw)/100))
      suspension_towers=sheet.cell(row=row_number, column=8).value
      #single suspension assembly
      sheet.cell(row=row_number, column=9).value=suspension_towers
      single_suspension_assembly=suspension_towers
      #single tension assembly for dead end location 
      sheet.cell(row=row_number, column=10).value=2
      single_tension_assembly_dead_end= sheet.cell(row=row_number, column=10).value
      #Double tension assembly for joint box location
      sheet.cell(row=row_number, column=11).value=joint_box-single_tension_assembly_dead_end
      double_tension_assembly_joint_box_location= sheet.cell(row=row_number, column=11).value
      #Double tension assembly for pass through
      sheet.cell(row=row_number, column=12).value=tension_towers-(single_tension_assembly_dead_end+double_tension_assembly_joint_box_location)
      double_tension_assembly_pass_through=sheet.cell(row=row_number, column=12).value
      #Vibration damper wirh protection rod
      sheet.cell(row=row_number, column=13).value=tension_towers*4+suspension_towers*2
      vibration_damper=sheet.cell(row=row_number, column=13).value
      #Surplus cable support
      sheet.cell(row=row_number, column=15).value=joint_box
      surplus_cable_support=sheet.cell(row=row_number, column=15).value
      #Downlead Clamp
      sheet.cell(row=row_number, column=17).value=surplus_cable_support*round(tower_height/2)
      downlead_clamp=sheet.cell(row=row_number, column=17).value
      #FODP
      sheet.cell(row=row_number, column=18).value=2
      fodp=sheet.cell(row=row_number, column=18).value
      #Approach Cable
      sheet.cell(row=row_number, column=19).value=fodp*500
      approach_cable=sheet.cell(row=row_number, column=19).value
      #HDPE Duct
      sheet.cell(row=row_number, column=20).value=approach_cable-(15*fodp)
      hdpe=sheet.cell(row=row_number, column=20).value
      #End Plug
      sheet.cell(row=row_number, column=21).value=fodp
      end_plug=sheet.cell(row=row_number, column=21).value
      #pushift couple
      sheet.cell(row=row_number, column=22).value=end_plug*5
      pushift_couple=sheet.cell(row=row_number, column=22).value
      #cable sealing
      sheet.cell(row=row_number, column=23).value=end_plug
      #U clamp
      sheet.cell(row=row_number, column=24).value=end_plug*25  
    elif sheet.cell(row=row_number, column=3).value==220:
      tower_height=37
      #Tower Height
      sheet.cell(row=row_number, column=16).value=tower_height
      #Actual OPGW from excel sheet
      opgw_route_length=sheet.cell(row=row_number, column=4).value
      #Joint box
      sheet.cell(row=row_number, column=14).value=round(1+(float(sheet.cell(row=row_number, column=4).value)/float(dl)))
      joint_box=sheet.cell(row=row_number, column=14).value
      #Total Length for 400KV so tower height = 35m
      sheet.cell(row=row_number, column=5).value=((opgw_route_length*1000*mf)+((tower_height*2)+sl+el)*(joint_box-1))/1000
      total_lenth=sheet.cell(row=row_number, column=5).value
      #Total Towers
      sheet.cell(row=row_number, column=6).value=round(1+(float(sheet.cell(row=row_number, column=4).value*1000))/rs)
      total_towers=sheet.cell(row=row_number, column=6).value
      #Tension Towers
      sheet.cell(row=row_number, column=7).value=round((total_towers*tw)/100)
      tension_towers=sheet.cell(row=row_number, column=7).value
      #Suspension Towers
      sheet.cell(row=row_number, column=8).value=round(total_towers-((total_towers*tw)/100))
      suspension_towers=sheet.cell(row=row_number, column=8).value
      #single suspension assembly
      sheet.cell(row=row_number, column=9).value=suspension_towers
      single_suspension_assembly=suspension_towers
      #single tension assembly for dead end location 
      sheet.cell(row=row_number, column=10).value=2
      single_tension_assembly_dead_end= sheet.cell(row=row_number, column=10).value
      #Double tension assembly for joint box location
      sheet.cell(row=row_number, column=11).value=joint_box-single_tension_assembly_dead_end
      double_tension_assembly_joint_box_location= sheet.cell(row=row_number, column=11).value
      #Double tension assembly for pass through
      sheet.cell(row=row_number, column=12).value=tension_towers-(single_tension_assembly_dead_end+double_tension_assembly_joint_box_location)
      #Vibration damper wirh protection rod
      sheet.cell(row=row_number, column=13).value=tension_towers*4+suspension_towers*2
      vibration_damper=sheet.cell(row=row_number, column=13).value
      #Surplus cable support
      sheet.cell(row=row_number, column=15).value=joint_box
      surplus_cable_support=sheet.cell(row=row_number, column=15).value
      #Downlead Clamp
      sheet.cell(row=row_number, column=17).value=surplus_cable_support*round(tower_height/2)
      downlead_clamp=sheet.cell(row=row_number, column=17).value
      #FODP
      sheet.cell(row=row_number, column=18).value=2
      fodp=sheet.cell(row=row_number, column=18).value
      #Approach Cable
      sheet.cell(row=row_number, column=19).value=fodp*500
      approach_cable=sheet.cell(row=row_number, column=19).value
      #HDPE Duct
      sheet.cell(row=row_number, column=20).value=approach_cable-(15*fodp)
      hdpe=sheet.cell(row=row_number, column=20).value
      #End Plug
      sheet.cell(row=row_number, column=21).value=fodp
      end_plug=sheet.cell(row=row_number, column=21).value
      #pushift couple
      sheet.cell(row=row_number, column=22).value=end_plug*5
      pushift_couple=sheet.cell(row=row_number, column=22).value
      #cable sealing
      sheet.cell(row=row_number, column=23).value=end_plug
      #U clamp
      sheet.cell(row=row_number, column=24).value=end_plug*25
    else:
      tower_height=35
      #Tower Height
      sheet.cell(row=row_number, column=16).value=tower_height
      #Actual OPGW from excel sheet
      opgw_route_length=sheet.cell(row=row_number, column=4).value
      #Joint box
      sheet.cell(row=row_number, column=14).value=round(1+(float(sheet.cell(row=row_number, column=4).value)/float(dl)))
      joint_box=sheet.cell(row=row_number, column=14).value
      #Total Length for 400KV so tower height = 35m
      sheet.cell(row=row_number, column=5).value=((opgw_route_length*1000*mf)+((tower_height*2)+sl+el)*(joint_box-1))/1000
      total_lenth=sheet.cell(row=row_number, column=5).value
      #Total Towers
      sheet.cell(row=row_number, column=6).value=round(1+(float(sheet.cell(row=row_number, column=4).value*1000))/rs)
      total_towers=sheet.cell(row=row_number, column=6).value
      #Tension Towers
      sheet.cell(row=row_number, column=7).value=round((total_towers*tw)/100)
      tension_towers=sheet.cell(row=row_number, column=7).value
      #Suspension Towers
      sheet.cell(row=row_number, column=8).value=round(total_towers-((total_towers*tw)/100))
      suspension_towers=sheet.cell(row=row_number, column=8).value
      #single suspension assembly
      sheet.cell(row=row_number, column=9).value=suspension_towers
      single_suspension_assembly=suspension_towers
      #single tension assembly for dead end location 
      sheet.cell(row=row_number, column=10).value=2
      single_tension_assembly_dead_end= sheet.cell(row=row_number, column=10).value
      #Double tension assembly for joint box location
      sheet.cell(row=row_number, column=11).value=joint_box-single_tension_assembly_dead_end
      double_tension_assembly_joint_box_location= sheet.cell(row=row_number, column=11).value
      #Double tension assembly for pass through
      sheet.cell(row=row_number, column=12).value=tension_towers-(single_tension_assembly_dead_end+double_tension_assembly_joint_box_location)
      #Vibration damper wirh protection rod
      sheet.cell(row=row_number, column=13).value=tension_towers*4+suspension_towers*2
      vibration_damper=sheet.cell(row=row_number, column=13).value
      #Surplus cable support
      sheet.cell(row=row_number, column=15).value=joint_box
      surplus_cable_support=sheet.cell(row=row_number, column=15).value
      #Downlead Clamp
      sheet.cell(row=row_number, column=17).value=surplus_cable_support*round(tower_height/2)
      downlead_clamp=sheet.cell(row=row_number, column=17).value
      #FODP
      sheet.cell(row=row_number, column=18).value=2
      fodp=sheet.cell(row=row_number, column=18).value
      #Approach Cable
      sheet.cell(row=row_number, column=19).value=fodp*500
      approach_cable=sheet.cell(row=row_number, column=19).value
      #HDPE Duct
      sheet.cell(row=row_number, column=20).value=approach_cable-(15*fodp)
      hdpe=sheet.cell(row=row_number, column=20).value
      #End Plug
      sheet.cell(row=row_number, column=21).value=fodp
      end_plug=sheet.cell(row=row_number, column=21).value
      #pushift couple
      sheet.cell(row=row_number, column=22).value=end_plug*5
      pushift_couple=sheet.cell(row=row_number, column=22).value
      #cable sealing
      sheet.cell(row=row_number, column=23).value=end_plug
      #U clamp
      sheet.cell(row=row_number, column=24).value=end_plug*25
    wb.save('test2.xlsx')
  return "Done! You can download the file with name test2.xlsx"
def Fiber_48():
  for row_number in range(2,max_rows+1):
    if sheet.cell(row=row_number, column=3).value==400:
      tower_height=40
      #Tower Height
      sheet.cell(row=row_number, column=16).value=tower_height
      #Actual OPGW from excel sheet
      opgw_route_length=sheet.cell(row=row_number, column=4).value
      #Joint box
      sheet.cell(row=row_number, column=14).value=round(1+(float(sheet.cell(row=row_number, column=4).value)/float(dl)))
      joint_box=sheet.cell(row=row_number, column=14).value
      #Total Length for 400KV so tower height = 35m
      sheet.cell(row=row_number, column=5).value=((opgw_route_length*1000*mf)+((tower_height*2)+sl+el)*(joint_box-1))/1000
      total_lenth=sheet.cell(row=row_number, column=5).value
      #Total Towers
      sheet.cell(row=row_number, column=6).value=round(1+(float(sheet.cell(row=row_number, column=4).value*1000))/rs)
      total_towers=sheet.cell(row=row_number, column=6).value
      #Tension Towers
      sheet.cell(row=row_number, column=7).value=round((total_towers*tw)/100)
      tension_towers=sheet.cell(row=row_number, column=7).value
      #Suspension Towers
      sheet.cell(row=row_number, column=8).value=round(total_towers-((total_towers*tw)/100))
      suspension_towers=sheet.cell(row=row_number, column=8).value
      #single suspension assembly
      sheet.cell(row=row_number, column=9).value=suspension_towers
      single_suspension_assembly=suspension_towers
      #single tension assembly for dead end location 
      sheet.cell(row=row_number, column=10).value=2
      single_tension_assembly_dead_end= sheet.cell(row=row_number, column=10).value
      #Double tension assembly for joint box location
      sheet.cell(row=row_number, column=11).value=joint_box-single_tension_assembly_dead_end
      double_tension_assembly_joint_box_location= sheet.cell(row=row_number, column=11).value
      #Double tension assembly for pass through
      sheet.cell(row=row_number, column=12).value=tension_towers-(single_tension_assembly_dead_end+double_tension_assembly_joint_box_location)
      double_tension_assembly_pass_through=sheet.cell(row=row_number, column=12).value
      #Vibration damper wirh protection rod
      sheet.cell(row=row_number, column=13).value=tension_towers*4+suspension_towers*2
      vibration_damper=sheet.cell(row=row_number, column=13).value
      #Surplus cable support
      sheet.cell(row=row_number, column=15).value=joint_box
      surplus_cable_support=sheet.cell(row=row_number, column=15).value
      #Downlead Clamp
      sheet.cell(row=row_number, column=17).value=surplus_cable_support*round(tower_height/2)
      downlead_clamp=sheet.cell(row=row_number, column=17).value
      #FODP
      sheet.cell(row=row_number, column=18).value=2
      fodp=sheet.cell(row=row_number, column=18).value
      #Approach Cable
      sheet.cell(row=row_number, column=19).value=fodp*500
      approach_cable=sheet.cell(row=row_number, column=19).value
      #HDPE Duct
      sheet.cell(row=row_number, column=20).value=approach_cable-(15*fodp)
      hdpe=sheet.cell(row=row_number, column=20).value
      #End Plug
      sheet.cell(row=row_number, column=21).value=fodp
      end_plug=sheet.cell(row=row_number, column=21).value
      #pushift couple
      sheet.cell(row=row_number, column=22).value=end_plug*5
      pushift_couple=sheet.cell(row=row_number, column=22).value
      #cable sealing
      sheet.cell(row=row_number, column=23).value=end_plug
      #U clamp
      sheet.cell(row=row_number, column=24).value=end_plug*25  
    elif sheet.cell(row=row_number, column=3).value==220:
      tower_height=37
      #Tower Height
      sheet.cell(row=row_number, column=16).value=tower_height
      #Actual OPGW from excel sheet
      opgw_route_length=sheet.cell(row=row_number, column=4).value
      #Joint box
      sheet.cell(row=row_number, column=14).value=round(1+(float(sheet.cell(row=row_number, column=4).value)/float(dl)))
      joint_box=sheet.cell(row=row_number, column=14).value
      #Total Length for 400KV so tower height = 35m
      sheet.cell(row=row_number, column=5).value=((opgw_route_length*1000*mf)+((tower_height*2)+sl+el)*(joint_box-1))/1000
      total_lenth=sheet.cell(row=row_number, column=5).value
      #Total Towers
      sheet.cell(row=row_number, column=6).value=round(1+(float(sheet.cell(row=row_number, column=4).value*1000))/rs)
      total_towers=sheet.cell(row=row_number, column=6).value
      #Tension Towers
      sheet.cell(row=row_number, column=7).value=round((total_towers*tw)/100)
      tension_towers=sheet.cell(row=row_number, column=7).value
      #Suspension Towers
      sheet.cell(row=row_number, column=8).value=round(total_towers-((total_towers*tw)/100))
      suspension_towers=sheet.cell(row=row_number, column=8).value
      #single suspension assembly
      sheet.cell(row=row_number, column=9).value=suspension_towers
      single_suspension_assembly=suspension_towers
      #single tension assembly for dead end location 
      sheet.cell(row=row_number, column=10).value=2
      single_tension_assembly_dead_end= sheet.cell(row=row_number, column=10).value
      #Double tension assembly for joint box location
      sheet.cell(row=row_number, column=11).value=joint_box-single_tension_assembly_dead_end
      double_tension_assembly_joint_box_location= sheet.cell(row=row_number, column=11).value
      #Double tension assembly for pass through
      sheet.cell(row=row_number, column=12).value=tension_towers-(single_tension_assembly_dead_end+double_tension_assembly_joint_box_location)
      #Vibration damper wirh protection rod
      sheet.cell(row=row_number, column=13).value=tension_towers*4+suspension_towers*2
      vibration_damper=sheet.cell(row=row_number, column=13).value
      #Surplus cable support
      sheet.cell(row=row_number, column=15).value=joint_box
      surplus_cable_support=sheet.cell(row=row_number, column=15).value
      #Downlead Clamp
      sheet.cell(row=row_number, column=17).value=surplus_cable_support*round(tower_height/2)
      downlead_clamp=sheet.cell(row=row_number, column=17).value
      #FODP
      sheet.cell(row=row_number, column=18).value=2
      fodp=sheet.cell(row=row_number, column=18).value
      #Approach Cable
      sheet.cell(row=row_number, column=19).value=fodp*500
      approach_cable=sheet.cell(row=row_number, column=19).value
      #HDPE Duct
      sheet.cell(row=row_number, column=20).value=approach_cable-(15*fodp)
      hdpe=sheet.cell(row=row_number, column=20).value
      #End Plug
      sheet.cell(row=row_number, column=21).value=fodp
      end_plug=sheet.cell(row=row_number, column=21).value
      #pushift couple
      sheet.cell(row=row_number, column=22).value=end_plug*5
      pushift_couple=sheet.cell(row=row_number, column=22).value
      #cable sealing
      sheet.cell(row=row_number, column=23).value=end_plug
      #U clamp
      sheet.cell(row=row_number, column=24).value=end_plug*25
    else:
      tower_height=35
      #Tower Height
      sheet.cell(row=row_number, column=16).value=tower_height
      #Actual OPGW from excel sheet
      opgw_route_length=sheet.cell(row=row_number, column=4).value
      #Joint box
      sheet.cell(row=row_number, column=14).value=round(1+(float(sheet.cell(row=row_number, column=4).value)/float(dl)))
      joint_box=sheet.cell(row=row_number, column=14).value
      #Total Length for 400KV so tower height = 35m
      sheet.cell(row=row_number, column=5).value=((opgw_route_length*1000*mf)+((tower_height*2)+sl+el)*(joint_box-1))/1000
      total_lenth=sheet.cell(row=row_number, column=5).value
      #Total Towers
      sheet.cell(row=row_number, column=6).value=round(1+(float(sheet.cell(row=row_number, column=4).value*1000))/rs)
      total_towers=sheet.cell(row=row_number, column=6).value
      #Tension Towers
      sheet.cell(row=row_number, column=7).value=round((total_towers*tw)/100)
      tension_towers=sheet.cell(row=row_number, column=7).value
      #Suspension Towers
      sheet.cell(row=row_number, column=8).value=round(total_towers-((total_towers*tw)/100))
      suspension_towers=sheet.cell(row=row_number, column=8).value
      #single suspension assembly
      sheet.cell(row=row_number, column=9).value=suspension_towers
      single_suspension_assembly=suspension_towers
      #single tension assembly for dead end location 
      sheet.cell(row=row_number, column=10).value=2
      single_tension_assembly_dead_end= sheet.cell(row=row_number, column=10).value
      #Double tension assembly for joint box location
      sheet.cell(row=row_number, column=11).value=joint_box-single_tension_assembly_dead_end
      double_tension_assembly_joint_box_location= sheet.cell(row=row_number, column=11).value
      #Double tension assembly for pass through
      sheet.cell(row=row_number, column=12).value=tension_towers-(single_tension_assembly_dead_end+double_tension_assembly_joint_box_location)
      #Vibration damper wirh protection rod
      sheet.cell(row=row_number, column=13).value=tension_towers*4+suspension_towers*2
      vibration_damper=sheet.cell(row=row_number, column=13).value
      #Surplus cable support
      sheet.cell(row=row_number, column=15).value=joint_box
      surplus_cable_support=sheet.cell(row=row_number, column=15).value
      #Downlead Clamp
      sheet.cell(row=row_number, column=17).value=surplus_cable_support*round(tower_height/2)
      downlead_clamp=sheet.cell(row=row_number, column=17).value
      #FODP
      sheet.cell(row=row_number, column=18).value=2
      fodp=sheet.cell(row=row_number, column=18).value
      #Approach Cable
      sheet.cell(row=row_number, column=19).value=fodp*500
      approach_cable=sheet.cell(row=row_number, column=19).value
      #HDPE Duct
      sheet.cell(row=row_number, column=20).value=approach_cable-(15*fodp)
      hdpe=sheet.cell(row=row_number, column=20).value
      #End Plug
      sheet.cell(row=row_number, column=21).value=fodp
      end_plug=sheet.cell(row=row_number, column=21).value
      #pushift couple
      sheet.cell(row=row_number, column=22).value=end_plug*5
      pushift_couple=sheet.cell(row=row_number, column=22).value
      #cable sealing
      sheet.cell(row=row_number, column=23).value=end_plug
      #U clamp
      sheet.cell(row=row_number, column=24).value=end_plug*25
    wb.save('test2.xlsx')
  return "Done! You can downlaod the file with name test2.xlsx"
def Fiber_24_and_48():
  for row_number in range(3,max_rows+1):
    if sheet.cell(row=row_number, column=3).value==400:
      tower_height=35 #height of the tower
      #24F given length
      fiber24=sheet.cell(row=row_number,column=4).value
      #48F given length
      fiber48=sheet.cell(row=row_number,column=5).value
      #Joint Box 24
      sheet.cell(row=row_number,column=24).value=round(1+(fiber24/dl))      
      joint_box_24=sheet.cell(row=row_number,column=24).value
      #Joint Box 48
      sheet.cell(row=row_number,column=25).value=round(1+(fiber48/dl))  
      joint_box_48=sheet.cell(row=row_number,column=25).value
      #24F Total OPGW length
      sheet.cell(row=row_number,column=6).value=(fiber24*1000*mf+((tower_height*2)+el+sl)*(joint_box_24-1))/1000
      tfiber24=sheet.cell(row=row_number,column=6).value
      #48F Total OPGW length
      sheet.cell(row=row_number,column=7).value=(fiber48*1000*mf+((tower_height*2)+el+sl)*(joint_box_48-1))/1000
      tfiber48=sheet.cell(row=row_number,column=7).value
      #Total towers 24F
      sheet.cell(row=row_number,column=8).value=round(1+((fiber24*1000)/rs))
      total_towers_24=sheet.cell(row=row_number,column=8).value
      #Total towers 48F
      sheet.cell(row=row_number,column=9).value=round(1+((fiber48*1000)/rs))
      total_towers_48=sheet.cell(row=row_number,column=9)
      #Tension towers 24F
      sheet.cell(row=row_number,column=10).value=round(total_towers_24*tw/100)
      tension_towers_24=sheet.cell(row=row_number,column=10).value
      #Tension towers 48F
      sheet.cell(row=row_number,column=11).value=round(total_towers_48*tw/100)
      tension_towers_48=sheet.cell(row=row_number,column=11).value
      #suspension towers 24F
      sheet.cell(row=row_number,column=12).value=total_towers_24-tension_towers_24
      suspension_towers_24=sheet.cell(row=row_number,column=12).value
      #suspension towers 48F
      sheet.cell(row=row_number,column=13).value=total_towers_48-tension_towers_48
      suspension_towers_48=sheet.cell(row=row_number,column=13).value
      #single suspension assembly 24F
      sheet.cell(row=row_number,column=14).value=suspension_towers_24
      single_suspension_assembly_24=sheet.cell(row=row_number,column=14).value
      #single suspension assembly 48F
      sheet.cell(row=row_number,column=15).value=suspension_towers_48
      single_suspension_assembly_48=sheet.cell(row=row_number,column=15).value
      #single tension assembly for dead end 24F
      sheet.cell(row=row_number,column=16).value=2
      single_suspension_assembly_dead_end_24=sheet.cell(row=row_number,column=16).value
      #single tension assembly for dead end 48F
      sheet.cell(row=row_number,column=17).value=2
      single_suspension_assembly_dead_end_24=sheet.cell(row=row_number,column=17).value
      #Double tension assembly joint box 24F
      sheet.cell(row=row_number,column=18).value=joint_box_24-single_suspension_assembly_dead_end_24
      double_tension_assembly_joint_box_24=sheet.cell(row=row_number,column=18).value
      #Double tension assembly joint box 48F
      sheet.cell(row=row_number,column=19).value=joint_box_48-single_suspension_assembly_dead_end_48
      double_tension_assembly_joint_box_48=sheet.cell(row=row_number,column=19).value
      #Double tension assembly pass through 24F
      sheet.cell(row=row_number,column=20).value=tension_towers_24-(single_suspension_assembly_dead_end_24+double_tension_assembly_joint_box_24)
      double_tension_assembly_pass_through_24=sheet.cell(row=row_number,column=20).value
      #Double tension assembly pass through 48F
      sheet.cell(row=row_number,column=21).value=tension_towers_48-(single_suspension_assembly_dead_end_48+double_tension_assembly_joint_box_48)
      double_tension_assembly_pass_through_48=sheet.cell(row=row_number,column=21).value
      #Vibration damper 24F
      sheet.cell(row=row_number,column=22).value=(tension_towers_24*4)+(suspension_towers_24*2)
      vibration_damper_24=sheet.cell(row=row_number,column=22).value
      #Vibration damper 48F
      sheet.cell(row=row_number,column=23).value=(tension_towers_48*4)+(suspension_towers_48*2)
      vibration_damper_48=sheet.cell(row=row_number,column=23).value
      #surplus cable 24F
      sheet.cell(row=row_number,column=26).value=joint_box_24
      surplus_cable_24=sheet.cell(row=row_number,column=26).value
      #surplus cable 48F
      sheet.cell(row=row_number,column=27).value=joint_box_48
      surplus_cable_48=sheet.cell(row=row_number,column=27).value
      #Downlead clamp 24F
      sheet.cell(row=row_number,column=28).value=surplus_cable_24*18
      downlead_clamp_24=sheet.cell(row=row_number,column=28).value
      #Downlead clamp 48F
      sheet.cell(row=row_number,column=29).value=surplus_cable_48*18
      downlead_clamp_48=sheet.cell(row=row_number,column=29).value
      #FODP 24F
      sheet.cell(row=row_number,column=30).value=2
      fodp_24=sheet.cell(row=row_number,column=30).value
      #FODP 48F
      sheet.cell(row=row_number,column=31).value=2
      fodp_48=sheet.cell(row=row_number,column=31).value
      #Approach cable 24F
      sheet.cell(row=row_number,column=32).value=500*fodp_24
      approach_cable_24=sheet.cell(row=row_number,column=32).value
      #Approach cable 48F
      sheet.cell(row=row_number,column=33).value=500*fodp_48
      approach_cable_48=sheet.cell(row=row_number,column=33).value
      #HDPE Duct 24F
      sheet.cell(row=row_number,column=34).value=(approach_cable_24-15)*fodp_24
      hdpe_duct_24=sheet.cell(row=row_number,column=34).value
      #HDPE Duct 48F
      sheet.cell(row=row_number,column=35).value=(approach_cable_48-15)*fodp_48
      hdpe_duct_24=sheet.cell(row=row_number,column=35).value
      #End Plug 24F
      sheet.cell(row=row_number,column=36).value=fodp_24
      end_plug_24=sheet.cell(row=row_number,column=36).value
      #End Plug 48F
      sheet.cell(row=row_number,column=37).value=fodp_48
      end_plug_48=sheet.cell(row=row_number,column=37).value
      #Pushfit Coupler 24F
      sheet.cell(row=row_number,column=38).value=end_plug_24*5
      pushift_coupler_24=sheet.cell(row=row_number,column=38).value
      #Pushfit Coupler 48F
      sheet.cell(row=row_number,column=39).value=end_plug_48*5
      pushift_coupler_48=sheet.cell(row=row_number,column=39).value
      #Cable Sealing 24F
      sheet.cell(row=row_number,column=40).value=end_plug_24
      cable_sealing_24=sheet.cell(row=row_number,column=40).value
      #Cable Sealing 48F
      sheet.cell(row=row_number,column=41).value=end_plug_48
      cable_sealing_48=sheet.cell(row=row_number,column=41).value
      #U clamp 24F
      sheet.cell(row=row_number,column=42).value=end_plug_24*25
      u_clamp_24=sheet.cell(row=row_number,column=42).value
      #U clamp 48F
      sheet.cell(row=row_number,column=43).value=end_plug_48*25
      u_clamp_48=sheet.cell(row=row_number,column=43).value  
    elif sheet.cell(row=row_number, column=3).value==220:
      r=90
    else:  
      d=10
    wb.save('test2.xlsx')
  return "Done! You can download the file with name test2.xlsx"
def default():
  return "Something goes wrong please check the entered values! :("
switcher = {
    1: Fiber_24,
    2: Fiber_48,
    3: Fiber_24_and_48
    }
def case(options):
    return switcher.get(options, default)()
print(switcher(int(options))

import openpyxl
wb=openpyxl.load_workbook('test1.xlsx')
sheet=wb.active
max_rows=sheet.max_row
max_columns=sheet.max_column
row_number=2
column_number=8
print(sheet.cell(row=row_number, column=column_number).value)

print (":(")