# -*- coding: utf-8 -*-
"""BOQ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rsvIHCqbPg7cooPxHu9hecKNLa1RX5so
"""

!git clone https://github.com/surya9teja/BOQ.git

sl=float(input("Splicing Lenght(m): "))
el=float(input("Extra length(m): "))
mf=float(input("multiply factor for OPGW total length: "))
rs=float(input("Rulling span length(m): "))
tw=float(input("Tension tower(%): "))
sw=100-int(tw)
dl=input("Drum Lenght(Km): ")
print ("Splicing Lenght(m):",sl)
print ("Extra lenght:",el)
print ("Percentage extra for OPGW:",mf)
print ("Rulling span lenght:",rs)
print ("Tension tower:",tw)
print ("suspension tower:",sw)
print ("Drum Lenght(Km):", dl)

import openpyxl
wb=openpyxl.load_workbook('test.xlsx')
sheet=wb.active
max_rows=sheet.max_row
max_columns=sheet.max_column
for row_number in range(2,max_rows):
  if sheet.cell(row=row_number, column=3).value==400:
    tower_height=35
    #Tower Height
    sheet.cell(row=row_number, column=16).value=tower_height
    #Actual OPGW from excel sheet
    opgw_route_length=sheet.cell(row=row_number, column=4).value
    #Joint box
    sheet.cell(row=row_number, column=14).value=round(1+(float(sheet.cell(row=row_number, column=4).value)/float(dl)))
    joint_box=sheet.cell(row=row_number, column=14).value
    #Total Length for 400KV so tower height = 35m
    sheet.cell(row=row_number, column=5).value=((opgw_route_length*1000*mf)+((tower_height*2)+sl+el)*(joint_box-1))/1000
    total_lenth=sheet.cell(row=row_number, column=5).value
    #Total Towers
    sheet.cell(row=row_number, column=6).value=round(1+(float(sheet.cell(row=row_number, column=4).value*1000))/rs)
    total_towers=sheet.cell(row=row_number, column=6).value
    #Tension Towers
    sheet.cell(row=row_number, column=7).value=round((total_towers*tw)/100)
    tension_towers=sheet.cell(row=row_number, column=7).value
    #Suspension Towers
    sheet.cell(row=row_number, column=8).value=round(total_towers-((total_towers*tw)/100))
    suspension_towers=sheet.cell(row=row_number, column=8).value
    #single suspension assembly
    sheet.cell(row=row_number, column=9).value=suspension_towers
    single_suspension_assembly=suspension_towers
    #single tension assembly for dead end location 
    sheet.cell(row=row_number, column=10).value=2
    single_tension_assembly_dead_end= sheet.cell(row=row_number, column=10).value
    #Double tension assembly for joint box location
    sheet.cell(row=row_number, column=11).value=joint_box-single_tension_assembly_dead_end
    double_tension_assembly_joint_box_location= sheet.cell(row=row_number, column=11).value
    #Double tension assembly for pass through
    sheet.cell(row=row_number, column=12).value=tension_towers-(single_tension_assembly_dead_end+double_tension_assembly_joint_box_location)
    double_tension_assembly_pass_through=sheet.cell(row=row_number, column=12).value
    #Vibration damper wirh protection rod
    sheet.cell(row=row_number, column=13).value=tension_towers*4+suspension_towers*2
    vibration_damper=sheet.cell(row=row_number, column=13).value
    #Surplus cable support
    sheet.cell(row=row_number, column=15).value=joint_box
    surplus_cable_support=sheet.cell(row=row_number, column=15).value
    #Downlead Clamp
    sheet.cell(row=row_number, column=17).value=surplus_cable_support*round(tower_height/2)
    downlead_clamp=sheet.cell(row=row_number, column=17).value
    #FODP
    sheet.cell(row=row_number, column=18).value=2
    fodp=sheet.cell(row=row_number, column=18).value
    #Approach Cable
    sheet.cell(row=row_number, column=19).value=fodp*500
    approach_cable=sheet.cell(row=row_number, column=19).value
    #HDPE Duct
    sheet.cell(row=row_number, column=20).value=approach_cable-(15*fodp)
    hdpe=sheet.cell(row=row_number, column=20).value
    #End Plug
    sheet.cell(row=row_number, column=21).value=fodp
    end_plug=sheet.cell(row=row_number, column=21).value
    #pushift couple
    sheet.cell(row=row_number, column=22).value=end_plug*5
    pushift_couple=sheet.cell(row=row_number, column=22).value
    #cable sealing
    sheet.cell(row=row_number, column=23).value=end_plug
    #U clamp
    sheet.cell(row=row_number, column=24).value=end_plug*25  
  elif sheet.cell(row=row_number, column=3).value==220:
    tower_height=32
    #Tower Height
    sheet.cell(row=row_number, column=16).value=tower_height
    #Actual OPGW from excel sheet
    opgw_route_length=sheet.cell(row=row_number, column=4).value
    #Joint box
    sheet.cell(row=row_number, column=14).value=round(1+(float(sheet.cell(row=row_number, column=4).value)/float(dl)))
    joint_box=sheet.cell(row=row_number, column=14).value
    #Total Length for 400KV so tower height = 35m
    sheet.cell(row=row_number, column=5).value=((opgw_route_length*1000*mf)+((tower_height*2)+sl+el)*(joint_box-1))/1000
    total_lenth=sheet.cell(row=row_number, column=5).value
    #Total Towers
    sheet.cell(row=row_number, column=6).value=round(1+(float(sheet.cell(row=row_number, column=4).value*1000))/rs)
    total_towers=sheet.cell(row=row_number, column=6).value
    #Tension Towers
    sheet.cell(row=row_number, column=7).value=round((total_towers*tw)/100)
    tension_towers=sheet.cell(row=row_number, column=7).value
    #Suspension Towers
    sheet.cell(row=row_number, column=8).value=round(total_towers-((total_towers*tw)/100))
    suspension_towers=sheet.cell(row=row_number, column=8).value
    #single suspension assembly
    sheet.cell(row=row_number, column=9).value=suspension_towers
    single_suspension_assembly=suspension_towers
    #single tension assembly for dead end location 
    sheet.cell(row=row_number, column=10).value=2
    single_tension_assembly_dead_end= sheet.cell(row=row_number, column=10).value
    #Double tension assembly for joint box location
    sheet.cell(row=row_number, column=11).value=joint_box-single_tension_assembly_dead_end
    double_tension_assembly_joint_box_location= sheet.cell(row=row_number, column=11).value
    #Double tension assembly for pass through
    sheet.cell(row=row_number, column=12).value=tension_towers-(single_tension_assembly_dead_end+double_tension_assembly_joint_box_location)
    #Vibration damper wirh protection rod
    sheet.cell(row=row_number, column=13).value=tension_towers*4+suspension_towers*2
    vibration_damper=sheet.cell(row=row_number, column=13).value
    #Surplus cable support
    sheet.cell(row=row_number, column=15).value=joint_box
    surplus_cable_support=sheet.cell(row=row_number, column=15).value
    #Downlead Clamp
    sheet.cell(row=row_number, column=17).value=surplus_cable_support*round(tower_height/2)
    downlead_clamp=sheet.cell(row=row_number, column=17).value
    #FODP
    sheet.cell(row=row_number, column=18).value=2
    fodp=sheet.cell(row=row_number, column=18).value
    #Approach Cable
    sheet.cell(row=row_number, column=19).value=fodp*500
    approach_cable=sheet.cell(row=row_number, column=19).value
    #HDPE Duct
    sheet.cell(row=row_number, column=20).value=approach_cable-(15*fodp)
    hdpe=sheet.cell(row=row_number, column=20).value
    #End Plug
    sheet.cell(row=row_number, column=21).value=fodp
    end_plug=sheet.cell(row=row_number, column=21).value
    #pushift couple
    sheet.cell(row=row_number, column=22).value=end_plug*5
    pushift_couple=sheet.cell(row=row_number, column=22).value
    #cable sealing
    sheet.cell(row=row_number, column=23).value=end_plug
    #U clamp
    sheet.cell(row=row_number, column=24).value=end_plug*25
  else:
    tower_height=30
    #Tower Height
    sheet.cell(row=row_number, column=16).value=tower_height
    #Actual OPGW from excel sheet
    opgw_route_length=sheet.cell(row=row_number, column=4).value
    #Joint box
    sheet.cell(row=row_number, column=14).value=round(1+(float(sheet.cell(row=row_number, column=4).value)/float(dl)))
    joint_box=sheet.cell(row=row_number, column=14).value
    #Total Length for 400KV so tower height = 35m
    sheet.cell(row=row_number, column=5).value=((opgw_route_length*1000*mf)+((tower_height*2)+sl+el)*(joint_box-1))/1000
    total_lenth=sheet.cell(row=row_number, column=5).value
    #Total Towers
    sheet.cell(row=row_number, column=6).value=round(1+(float(sheet.cell(row=row_number, column=4).value*1000))/rs)
    total_towers=sheet.cell(row=row_number, column=6).value
    #Tension Towers
    sheet.cell(row=row_number, column=7).value=round((total_towers*tw)/100)
    tension_towers=sheet.cell(row=row_number, column=7).value
    #Suspension Towers
    sheet.cell(row=row_number, column=8).value=round(total_towers-((total_towers*tw)/100))
    suspension_towers=sheet.cell(row=row_number, column=8).value
    #single suspension assembly
    sheet.cell(row=row_number, column=9).value=suspension_towers
    single_suspension_assembly=suspension_towers
    #single tension assembly for dead end location 
    sheet.cell(row=row_number, column=10).value=2
    single_tension_assembly_dead_end= sheet.cell(row=row_number, column=10).value
    #Double tension assembly for joint box location
    sheet.cell(row=row_number, column=11).value=joint_box-single_tension_assembly_dead_end
    double_tension_assembly_joint_box_location= sheet.cell(row=row_number, column=11).value
    #Double tension assembly for pass through
    sheet.cell(row=row_number, column=12).value=tension_towers-(single_tension_assembly_dead_end+double_tension_assembly_joint_box_location)
    #Vibration damper wirh protection rod
    sheet.cell(row=row_number, column=13).value=tension_towers*4+suspension_towers*2
    vibration_damper=sheet.cell(row=row_number, column=13).value
    #Surplus cable support
    sheet.cell(row=row_number, column=15).value=joint_box
    surplus_cable_support=sheet.cell(row=row_number, column=15).value
    #Downlead Clamp
    sheet.cell(row=row_number, column=17).value=surplus_cable_support*round(tower_height/2)
    downlead_clamp=sheet.cell(row=row_number, column=17).value
    #FODP
    sheet.cell(row=row_number, column=18).value=2
    fodp=sheet.cell(row=row_number, column=18).value
    #Approach Cable
    sheet.cell(row=row_number, column=19).value=fodp*500
    approach_cable=sheet.cell(row=row_number, column=19).value
    #HDPE Duct
    sheet.cell(row=row_number, column=20).value=approach_cable-(15*fodp)
    hdpe=sheet.cell(row=row_number, column=20).value
    #End Plug
    sheet.cell(row=row_number, column=21).value=fodp
    end_plug=sheet.cell(row=row_number, column=21).value
    #pushift couple
    sheet.cell(row=row_number, column=22).value=end_plug*5
    pushift_couple=sheet.cell(row=row_number, column=22).value
    #cable sealing
    sheet.cell(row=row_number, column=23).value=end_plug
    #U clamp
    sheet.cell(row=row_number, column=24).value=end_plug*25
  wb.save('test1.xlsx')

import openpyxl
wb=openpyxl.load_workbook('test1.xlsx')
sheet=wb.active
max_rows=sheet.max_row
max_columns=sheet.max_column
row_number=2
column_number=8
print(sheet.cell(row=row_number, column=column_number).value)

!pwd